'use client'
import {useEffect,useState} from 'react'
import {createClient} from '@supabase/supabase-js'
const sb=createClient('https://ldwgsogeqreywbqulqyj.supabase.co','sb_publishable_heJuVcHJZcNkQm2w5Q2dIA_bUTPZTOE')
const cats=['Alimentaire','Boissons','Consommable','Entretien','Mobilier','Energie','Assurance','Telephonie']
const euro=n=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(Number(n||0))
const st={width:'100%',boxSizing:'border-box',padding:11,marginTop:6}
export default function Factures(){
 const [user,setUser]=useState(undefined),[ests,setEsts]=useState([]),[rows,setRows]=useState([]),[edit,setEdit]=useState(null),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{sb.auth.getUser().then(({data})=>setUser(data?.user||null))},[])
 useEffect(()=>{if(user)load()},[user])
 async function load(){const [{data:e},{data:i}]=await Promise.all([sb.from('establishments').select('id,name').eq('active',true),sb.from('supplier_invoices').select('*').order('invoice_date',{ascending:false}).limit(1000)]);setEsts(e||[]);setRows(i||[])}
 const name=id=>ests.find(x=>x.id===id)?.name||'—'
 function open(x){setMsg('');setEdit({...x,amount_ht:String(x.amount_ht??''),vat_amount:String(x.vat_amount??''),due_date:x.due_date||''})}
 async function save(e){e.preventDefault();setBusy(true);setMsg('');const payload={establishment_id:edit.establishment_id,invoice_date:edit.invoice_date,supplier:edit.supplier.trim(),category:edit.category,invoice_number:edit.invoice_number?.trim()||null,amount_ht:Number(edit.amount_ht||0),vat_amount:Number(edit.vat_amount||0),due_date:edit.due_date||null,paid:!!edit.paid};const {error}=await sb.from('supplier_invoices').update(payload).eq('id',edit.id);setBusy(false);if(error)return setMsg('Erreur : '+error.message);setMsg('✓ Facture modifiée.');setEdit(null);await load()}
 async function remove(x){if(!window.confirm(`Supprimer définitivement la facture ${x.invoice_number||''} de ${x.supplier} ?`))return;setBusy(true);setMsg('');const {error}=await sb.from('supplier_invoices').delete().eq('id',x.id);setBusy(false);if(error)return setMsg('Erreur : '+error.message);if(edit?.id===x.id)setEdit(null);setMsg('✓ Facture supprimée.');await load()}
 if(user===undefined)return <main><section><p>Chargement…</p></section></main>
 if(!user)return <main><section><h2>Accès protégé</h2><p>Connectez-vous d’abord à Maison Oddos.</p><a href="/"><button>Retour à la connexion</button></a></section></main>
 return <main><header><div><div className="brand">MAISON ODDOS</div><h1>Gestion des factures</h1></div><a href="/"><button>← Pilotage</button></a></header><section>
 {edit&&<div className="formCard" style={{maxWidth:850,marginBottom:24}}><h2>Modifier la facture</h2><form onSubmit={save}><div className="grid"><label>Restaurant<select required value={edit.establishment_id} onChange={e=>setEdit({...edit,establishment_id:e.target.value})} style={st}>{ests.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Date<input type="date" required value={edit.invoice_date} onChange={e=>setEdit({...edit,invoice_date:e.target.value})} style={st}/></label><label>Fournisseur<input required value={edit.supplier} onChange={e=>setEdit({...edit,supplier:e.target.value})} style={st}/></label><label>Catégorie<select required value={edit.category} onChange={e=>setEdit({...edit,category:e.target.value})} style={st}>{cats.map(c=><option key={c}>{c}</option>)}</select></label><label>N° facture<input value={edit.invoice_number||''} onChange={e=>setEdit({...edit,invoice_number:e.target.value})} style={st}/></label><label>Montant HT<input type="number" min="0" step="0.01" required value={edit.amount_ht} onChange={e=>setEdit({...edit,amount_ht:e.target.value})} style={st}/></label><label>TVA<input type="number" min="0" step="0.01" value={edit.vat_amount} onChange={e=>setEdit({...edit,vat_amount:e.target.value})} style={st}/></label><label>Échéance<input type="date" value={edit.due_date} onChange={e=>setEdit({...edit,due_date:e.target.value})} style={st}/></label></div><p><b>TTC : {euro(Number(edit.amount_ht||0)+Number(edit.vat_amount||0))}</b></p><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><button disabled={busy}>Enregistrer les modifications</button><button type="button" onClick={()=>setEdit(null)}>Annuler</button></div></form></div>}
 {msg&&<p><b>{msg}</b></p>}<h2>Factures fournisseurs</h2><div className="table"><table><thead><tr><th>Date</th><th>Établissement</th><th>Fournisseur</th><th>Catégorie</th><th>HT</th><th>TVA</th><th>TTC</th><th>Actions</th></tr></thead><tbody>{rows.length?rows.map(x=><tr key={x.id}><td>{x.invoice_date}</td><td>{name(x.establishment_id)}</td><td>{x.supplier}</td><td>{x.category}</td><td>{euro(x.amount_ht)}</td><td>{euro(x.vat_amount)}</td><td><b>{euro(Number(x.amount_ht||0)+Number(x.vat_amount||0))}</b></td><td><div style={{display:'flex',gap:6,flexWrap:'wrap'}}><button onClick={()=>open(x)}>Ouvrir / Modifier</button><button onClick={()=>remove(x)} disabled={busy}>Supprimer</button></div></td></tr>):<tr><td colSpan="8">Aucune facture.</td></tr>}</tbody></table></div></section></main>
}