'use client'
import {useEffect,useState} from 'react'
import {createClient} from '@supabase/supabase-js'
const sb=createClient('https://ldwgsogeqreywbqulqyj.supabase.co','sb_publishable_heJuVcHJZcNkQm2w5Q2dIA_bUTPZTOE')
const money=n=>new Intl.NumberFormat('fr-FR',{maximumFractionDigits:0}).format(Number(n||0))+' €'
export default function DirectionFinanceChart(){
 const [data,setData]=useState(null)
 useEffect(()=>{let stop=false,timer
  async function load(){const {data:{user}}=await sb.auth.getUser();if(!user||stop)return;const [{data:sales},{data:invoices},{data:employees},{data:fixed}]=await Promise.all([sb.from('daily_sales').select('establishment_id,business_date,lunch_sales_ht,dinner_sales_ht'),sb.from('supplier_invoices').select('establishment_id,invoice_date,amount_ht'),sb.from('employees').select('establishment_id,monthly_loaded_cost,active').eq('active',true),sb.from('fixed_charges').select('establishment_id,month,amount')]);setData({sales:sales||[],invoices:invoices||[],employees:employees||[],fixed:fixed||[]})}
  load();timer=setInterval(load,30000);return()=>{stop=true;clearInterval(timer)}
 },[])
 useEffect(()=>{if(!data)return;let timer
  const render=()=>{const main=document.querySelector('main');if(!main)return;const title=[...main.querySelectorAll('h3')].find(x=>x.textContent?.trim()==='Évolution CA / Charges');if(!title)return;const card=title.closest('.formCard');if(!card)return;let host=card.querySelector('[data-finance-chart]');if(!host){const old=[...card.children].find(x=>x.querySelector?.('svg'));if(old)old.style.display='none';host=document.createElement('div');host.dataset.financeChart='1';card.appendChild(host)}
   const estSel=[...main.querySelectorAll('select')].find(x=>[...x.options].some(o=>o.textContent?.includes('CONSOLIDÉ'))),est=estSel?.value||'all';const monthInput=card.querySelector('input[type="month"]'),yearInput=card.querySelector('input[type="number"]'),month=monthInput?.value||new Date().toISOString().slice(0,7),year=yearInput?.value||new Date().getFullYear().toString(),isMonth=!!monthInput;const filt=(arr)=>est==='all'?arr:arr.filter(x=>x.establishment_id===est),emps=filt(data.employees),payroll=emps.reduce((a,x)=>a+Number(x.monthly_loaded_cost||0),0),fixedRows=filt(data.fixed),salesRows=filt(data.sales),invRows=filt(data.invoices);let rows=[]
   if(isMonth){const [yy,mm]=month.split('-').map(Number),days=new Date(yy,mm,0).getDate(),fixedMonth=fixedRows.filter(x=>String(x.month||'').startsWith(month)).reduce((a,x)=>a+Number(x.amount||0),0);rows=Array.from({length:days},(_,i)=>({label:String(i+1),ca:0,achats:0,personnel:i<22?payroll/22:0,fixes:i<22?fixedMonth/22:0}));salesRows.filter(x=>x.business_date?.startsWith(month)).forEach(x=>{const i=Number(x.business_date.slice(8,10))-1;if(rows[i])rows[i].ca+=Number(x.lunch_sales_ht||0)+Number(x.dinner_sales_ht||0)});invRows.filter(x=>x.invoice_date?.startsWith(month)).forEach(x=>{const i=Number(x.invoice_date.slice(8,10))-1;if(rows[i])rows[i].achats+=Number(x.amount_ht||0)})}
   else{const names=['Jan','Fév','Mar','Avr','Mai','Juin','Juil','Août','Sep','Oct','Nov','Déc'];rows=names.map((label,i)=>({label,ca:0,achats:0,personnel:payroll,fixes:fixedRows.filter(x=>String(x.month||'').startsWith(year+'-'+String(i+1).padStart(2,'0'))).reduce((a,x)=>a+Number(x.amount||0),0)}));salesRows.filter(x=>x.business_date?.startsWith(year+'-')).forEach(x=>rows[Number(x.business_date.slice(5,7))-1].ca+=Number(x.lunch_sales_ht||0)+Number(x.dinner_sales_ht||0));invRows.filter(x=>x.invoice_date?.startsWith(year+'-')).forEach(x=>rows[Number(x.invoice_date.slice(5,7))-1].achats+=Number(x.amount_ht||0))}
   const W=900,H=330,p=52,max=Math.max(1,...rows.flatMap(r=>[r.ca,r.achats,r.personnel,r.fixes]))*1.08,x=i=>p+i*(W-2*p)/Math.max(1,rows.length-1),y=v=>H-p-(Number(v||0)/max)*(H-2*p),path=k=>rows.map((r,i)=>(i?'L':'M')+x(i).toFixed(1)+' '+y(r[k]).toFixed(1)).join(' '),dots=(k,c)=>rows.map((r,i)=>`<circle cx="${x(i)}" cy="${y(r[k])}" r="3.5" fill="${c}"><title>${r.label} — ${money(r[k])}</title></circle>`).join(''),labels=rows.map((r,i)=>(rows.length<=12||i%4===0||i===rows.length-1)?`<text x="${x(i)}" y="${H-12}" text-anchor="middle" font-size="11" fill="#5f665e">${r.label}</text>`:'').join('');
   host.innerHTML=`<div style="overflow-x:auto;margin-top:18px"><div style="min-width:700px"><div style="display:flex;gap:20px;flex-wrap:wrap;justify-content:center;margin:8px 0 12px;font-size:14px;font-weight:700"><span style="color:#185c2b">● CA</span><span style="color:#2474d8">● Achats</span><span style="color:#e62b26">● Personnel</span><span style="color:#f39a0a">● Charges fixes</span></div><svg viewBox="0 0 ${W} ${H}" style="width:100%;height:330px;background:#fff;border-radius:12px">${[0,.25,.5,.75,1].map(v=>`<g><line x1="${p}" y1="${y(max*v)}" x2="${W-p}" y2="${y(max*v)}" stroke="#dfe3dd"/><text x="5" y="${y(max*v)+4}" font-size="11" fill="#5f665e">${money(max*v)}</text></g>`).join('')}<path d="${path('ca')}" fill="none" stroke="#185c2b" stroke-width="4"/>${dots('ca','#185c2b')}<path d="${path('achats')}" fill="none" stroke="#2474d8" stroke-width="3"/>${dots('achats','#2474d8')}<path d="${path('personnel')}" fill="none" stroke="#e62b26" stroke-width="3"/>${dots('personnel','#e62b26')}<path d="${path('fixes')}" fill="none" stroke="#f39a0a" stroke-width="3"/>${dots('fixes','#f39a0a')}${labels}</svg></div></div>`
  }
  render();const obs=new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(render,80)});obs.observe(document.body,{childList:true,subtree:true,attributes:true});document.addEventListener('change',render);document.addEventListener('click',()=>setTimeout(render,80));return()=>{clearTimeout(timer);obs.disconnect();document.removeEventListener('change',render)}
 },[data]);return null
}
