'use client'
import {useEffect,useState} from 'react'
import {createClient} from '@supabase/supabase-js'
const sb=createClient('https://ldwgsogeqreywbqulqyj.supabase.co','sb_publishable_heJuVcHJZcNkQm2w5Q2dIA_bUTPZTOE')
const euro=n=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(Number(n||0))
export default function DirectionPersonnelCost(){
 const [employees,setEmployees]=useState([])
 useEffect(()=>{let alive=true;async function load(){const {data:u}=await sb.auth.getUser();if(!u?.user)return;const {data}=await sb.from('employees').select('establishment_id,monthly_loaded_cost,active').eq('active',true);if(alive)setEmployees(data||[])}load();const timer=setInterval(load,10000);return()=>{alive=false;clearInterval(timer)}},[])
 useEffect(()=>{const apply=()=>{const direction=[...document.querySelectorAll('nav button')].find(b=>b.textContent.trim()==='Direction');if(direction&&!direction.classList.contains('active'))return;const select=[...document.querySelectorAll('main select')].find(s=>[...s.options].some(o=>o.textContent.includes('CONSOLIDÉ')));const selected=select?.value||'all';const monthly=employees.filter(e=>selected==='all'||e.establishment_id===selected).reduce((a,e)=>a+Number(e.monthly_loaded_cost||0),0);const label=[...document.querySelectorAll('main span,main div,main p')].find(el=>el.children.length===0&&el.textContent.trim()==='Personnel');if(!label)return;const card=label.parentElement;if(!card)return;const amount=card.querySelector('strong')||[...card.children].find(el=>el!==label&&/^-?[\d\s.,]+\s*€$/.test(el.textContent.trim()));if(amount)amount.textContent=euro(monthly/22);let detail=card.querySelector('[data-personnel-cost-detail]');if(!detail){detail=document.createElement('small');detail.dataset.personnelCostDetail='1';detail.style.display='block';detail.style.marginTop='6px';card.appendChild(detail)}detail.textContent=`Moyenne / jour · ${euro(monthly)} / mois ÷ 22`};apply();const timer=setInterval(apply,300);document.addEventListener('change',apply,true);return()=>{clearInterval(timer);document.removeEventListener('change',apply,true)}},[employees])
 return null
}