'use client'
import {useEffect,useState} from 'react'
import {createClient} from '@supabase/supabase-js'
const sb=createClient('https://ldwgsogeqreywbqulqyj.supabase.co','sb_publishable_heJuVcHJZcNkQm2w5Q2dIA_bUTPZTOE')
const euro=n=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(Number(n||0))
export default function DirectionPersonnelCost(){
 const [employees,setEmployees]=useState([])
 useEffect(()=>{let alive=true;async function load(){const {data:u}=await sb.auth.getUser();if(!u?.user)return;const {data}=await sb.from('employees').select('establishment_id,monthly_loaded_cost,active').eq('active',true);if(alive)setEmployees(data||[])}load();const timer=setInterval(load,10000);return()=>{alive=false;clearInterval(timer)}},[])
 useEffect(()=>{let last='';const apply=()=>{const active=[...document.querySelectorAll('nav button.active')].some(b=>b.textContent.trim()==='Direction');if(!active)return;const select=[...document.querySelectorAll('main select')].find(s=>[...s.options].some(o=>o.textContent.includes('CONSOLIDÉ')));const selected=select?.value||'all';const monthly=employees.filter(e=>selected==='all'||e.establishment_id===selected).reduce((a,e)=>a+Number(e.monthly_loaded_cost||0),0);const candidates=[...document.querySelectorAll('main .card, main .formCard, main section div')];const card=candidates.find(c=>{const children=[...c.children];return children.some(x=>x.textContent.trim()==='Personnel')&&children.some(x=>/€/.test(x.textContent))});if(!card)return;const amount=[...card.children].find(x=>/€/.test(x.textContent)&&x.textContent.trim()!=='Personnel');if(amount&&amount.textContent!==euro(monthly/22))amount.textContent=euro(monthly/22);let small=card.querySelector('[data-personnel-cost-detail]');if(!small){small=document.createElement('small');small.dataset.personnelCostDetail='1';small.style.display='block';small.style.marginTop='6px';card.appendChild(small)}const detail=`Coût moyen / jour · ${euro(monthly)} / mois ÷ 22`;if(small.textContent!==detail)small.textContent=detail;last=selected};const timer=setInterval(apply,500);apply();document.addEventListener('change',apply);return()=>{clearInterval(timer);document.removeEventListener('change',apply)}},[employees])
 return null
}