'use client'
import {useEffect,useMemo,useState} from 'react'
import {createPortal} from 'react-dom'
import {createClient} from '@supabase/supabase-js'
const sb=createClient('https://ldwgsogeqreywbqulqyj.supabase.co','sb_publishable_heJuVcHJZcNkQm2w5Q2dIA_bUTPZTOE')
const VILLA='8395bf22-99cb-4a7b-9096-ca734d583d83',PARC='55c6e880-aa0c-40d6-9065-b5315b1a602a'
const normal=(id,d)=>id===VILLA?(d>=2&&d<=6):id===PARC?(d>=1&&d<=6):(d>=1&&d<=6)
export default function OpeningCalendar(){
 const [host,setHost]=useState(null),[open,setOpen]=useState(false),[rows,setRows]=useState([]),[saving,setSaving]=useState(false),[ctxKey,setCtxKey]=useState(''),[fixedCtx,setFixedCtx]=useState(null)
 const main=()=>document.querySelector('main')
 const context=()=>{const m=main();const s=[...m.querySelectorAll('select')].find(x=>[...x.options].some(o=>o.textContent?.includes('CONSOLIDÉ')));return{est:s?.value||'all',ym:m.querySelector('input[type="month"]')?.value||new Date().toISOString().slice(0,7)}}
 async function load(ctx){const {est,ym}=ctx||context();if(est==='all'){setRows([]);return}const {data}=await sb.from('opening_days').select('business_date,is_open').eq('establishment_id',est).gte('business_date',ym+'-01').lte('business_date',ym+'-31');setRows(data||[])}
 useEffect(()=>{const t=setInterval(()=>{const m=main();if(!m)return;const active=[...m.querySelectorAll('nav button')].find(b=>b.textContent.trim()==='Direction')?.classList.contains('active');if(!active){setHost(null);return}const card=[...m.querySelectorAll('.card')].find(c=>c.querySelector('span')?.textContent?.startsWith('Jours travaillés'));if(card){card.style.cursor='pointer';card.title='Cliquer pour gérer les jours d’ouverture';card.onclick=()=>{const c=context();setFixedCtx(c);setOpen(true);load(c)};const {est,ym}=context(),key=est+'|'+ym;if(key!==ctxKey){setCtxKey(key);load()}let h=document.getElementById('opening-calendar-host');if(!h){h=document.createElement('div');h.id='opening-calendar-host';m.appendChild(h)}setHost(h)}} ,500);return()=>clearInterval(t)},[])
 const {est,ym}=fixedCtx||{est:'all',ym:''};const map=useMemo(()=>Object.fromEntries(rows.map(x=>[x.business_date,x.is_open])),[rows])
 const days=useMemo(()=>{if(!ym||est==='all')return[];const [y,m]=ym.split('-').map(Number),n=new Date(y,m,0).getDate();return Array.from({length:n},(_,i)=>{const date=ym+'-'+String(i+1).padStart(2,'0'),dow=new Date(y,m-1,i+1).getDay();return{date,n:i+1,dow,isOpen:date in map?map[date]:normal(est,dow)}})},[ym,est,map])
 async function save(next){setRows(next.map(x=>({business_date:x.date,is_open:x.isOpen})));updateCard(next);setSaving(true);const {data:{user}}=await sb.auth.getUser();if(!user){setSaving(false);alert('Session expirée : reconnecte-toi.');return}const payload=next.map(x=>({establishment_id:est,business_date:x.date,is_open:x.isOpen,created_by:user.id,updated_at:new Date().toISOString()}));const {error}=await sb.from('opening_days').upsert(payload,{onConflict:'establishment_id,business_date'});setSaving(false);if(error){alert('Enregistrement impossible : '+error.message);await load();return}window.dispatchEvent(new Event('pilotage-refresh'))}
 const updateCard=next=>{const card=[...main().querySelectorAll('.card')].find(c=>c.querySelector('span')?.textContent?.startsWith('Jours travaillés'));const strong=card?.querySelector('strong');if(strong)strong.textContent=String(next.filter(x=>x.isOpen).length)}
 const toggle=d=>{if(saving)return;const next=days.map(x=>x.date===d.date?{...x,isOpen:!x.isOpen}:x);save(next)}
 const setAll=v=>{if(saving)return;const next=days.map(x=>({...x,isOpen:v}));save(next)}
 const habitual=()=>{if(saving)return;const next=days.map(x=>({...x,isOpen:normal(est,new Date(x.date+'T12:00:00').getDay())}));save(next)}
 const count=days.filter(x=>x.isOpen).length
 useEffect(()=>{if(!host||est==='all'||!ym)return;updateCard(days)},[host,est,ym,count])
 if(!host||!open)return null
 const names=['Dim','Lun','Mar','Mer','Jeu','Ven','Sam']
 return createPortal(<div style={{position:'fixed',inset:0,background:'rgba(0,0,0,.45)',zIndex:9999,display:'grid',placeItems:'center',padding:18}} onClick={()=>{setOpen(false);setFixedCtx(null)}}><div className="formCard" style={{width:'min(760px,96vw)',maxHeight:'90vh',overflow:'auto'}} onClick={e=>e.stopPropagation()}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><div><h2>Jours d’ouverture</h2><p>{ym} · <b>{count} jours ouverts</b></p></div><button onClick={()=>{setOpen(false);setFixedCtx(null)}}>Fermer</button></div>{est==='all'?<p>Sélectionne d’abord un établissement pour modifier son calendrier.</p>:<><div style={{display:'grid',gridTemplateColumns:'repeat(7,1fr)',gap:7}}>{names.map(x=><b key={x} style={{textAlign:'center'}}>{x}</b>)}{Array.from({length:new Date(Number(ym.slice(0,4)),Number(ym.slice(5,7))-1,1).getDay()}).map((_,i)=><span key={'e'+i}/>)}{days.map(d=><button key={d.date} disabled={saving} onClick={()=>toggle(d)} style={{padding:'12px 4px',borderRadius:9,border:'1px solid #ccc',background:d.isOpen?'#48633a':'#eee',color:d.isOpen?'white':'#777',fontWeight:700}}>{d.n}</button>)}</div><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:16}}><button disabled={saving} onClick={habitual}>Horaires habituels</button><button disabled={saving} onClick={()=>setAll(true)}>Tout ouvrir</button><button disabled={saving} onClick={()=>setAll(false)}>Tout fermer</button></div><p><small>Vert = ouvert · Gris = fermé. Chaque modification recalcule le pilotage.</small></p></>}</div></div>,host)
}