'use client'
import {useEffect,useMemo,useState} from 'react'
import {createClient} from '@supabase/supabase-js'
const sb=createClient('https://ldwgsogeqreywbqulqyj.supabase.co','sb_publishable_heJuVcHJZcNkQm2w5Q2dIA_bUTPZTOE')
const euro=n=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(Number(n||0))
export default function Home(){
 const [ests,setEsts]=useState([]),[sales,setSales]=useState([]),[invoices,setInvoices]=useState([]),[charges,setCharges]=useState([]),[tab,setTab]=useState('direction'),[selectedEst,setSelectedEst]=useState('all')
 useEffect(()=>{load()},[])
 async function load(){const [{data:e},{data:s},{data:i},{data:c}]=await Promise.all([sb.from('establishments').select('*').eq('active',true),sb.from('daily_sales').select('*').order('business_date',{ascending:false}).limit(100),sb.from('supplier_invoices').select('*').order('invoice_date',{ascending:false}).limit(100),sb.from('fixed_charges').select('*').order('month',{ascending:false}).limit(100)]);setEsts(e||[]);setSales(s||[]);setInvoices(i||[]);setCharges(c||[])}
 const fs=selectedEst==='all'?sales:sales.filter(x=>x.establishment_id===selectedEst),fi=selectedEst==='all'?invoices:invoices.filter(x=>x.establishment_id===selectedEst),fc=selectedEst==='all'?charges:charges.filter(x=>x.establishment_id===selectedEst)
 const totals=useMemo(()=>{const ca=fs.reduce((a,x)=>a+Number(x.lunch_sales_ht)+Number(x.dinner_sales_ht),0),covers=fs.reduce((a,x)=>a+Number(x.lunch_covers)+Number(x.dinner_covers),0),personnel=fs.reduce((a,x)=>a+Number(x.staff_cost),0),achats=fi.reduce((a,x)=>a+Number(x.amount_ht),0),fixes=fc.reduce((a,x)=>a+Number(x.amount),0);return{ca,covers,personnel,achats,fixes,result:ca-achats-personnel-fixes}},[fs,fi,fc])
 const name=id=>ests.find(e=>e.id===id)?.name||'—'
 return <main><header><div><div className="brand">MAISON ODDOS</div><h1>Pilotage Restaurants</h1></div><div className="user"><b>Mode développement</b><span>Accès temporairement ouvert</span></div></header>
 <section style={{paddingTop:16,paddingBottom:0}}><div className="formCard" style={{padding:16}}><label style={{margin:0,fontWeight:700}}>Établissement<select value={selectedEst} onChange={e=>setSelectedEst(e.target.value)} style={{marginTop:7}}><option value="all">CONSOLIDÉ — Tous les établissements</option>{ests.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div></section>
 <nav>{[['direction','Direction'],['scanner','Scanner'],['saisie','Saisie rapide'],['factures','Factures'],['stocks','Stocks'],['charges','Charges'],['historique','Historique']].map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{l}</button>)}</nav>
 {tab==='direction'&&<section><div className="hero"><div><span>{selectedEst==='all'?'Situation consolidée':name(selectedEst)}</span><h2>{euro(totals.ca)}</h2><small>Chiffre d’affaires HT enregistré</small></div><div className="result"><span>Résultat estimé</span><strong>{euro(totals.result)}</strong></div></div><div className="grid"><Card t="Couverts" v={totals.covers}/><Card t="Ticket moyen" v={euro(totals.covers?totals.ca/totals.covers:0)}/><Card t="Achats matière" v={euro(totals.achats)}/><Card t="Personnel" v={euro(totals.personnel)}/><Card t="Charges fixes" v={euro(totals.fixes)}/><Card t="Marge après charges" v={euro(totals.result)}/></div><h3>Dernières journées</h3><Table rows={fs.slice(0,8).map(x=>[x.business_date,name(x.establishment_id),euro(+x.lunch_sales_ht + +x.dinner_sales_ht),x.lunch_covers+x.dinner_covers])} heads={['Date','Établissement','CA HT','Couverts']}/></section>}
 {tab==='scanner'&&<section><div className="formCard"><h2>Scanner les documents</h2><p>Photographiez une facture fournisseur ou un Z de caisse depuis votre téléphone.</p><a href="/scan"><button>Ouvrir le scanner</button></a></div></section>}
 {tab==='saisie'&&<section><div className="formCard"><h2>Saisie rapide</h2><p>La saisie manuelle sera conservée comme solution de secours. Le scanner alimentera automatiquement cette partie après validation.</p></div></section>}
 {tab==='factures'&&<section><h2>Factures fournisseurs</h2><Table rows={fi.slice(0,10).map(x=>[x.invoice_date,name(x.establishment_id),x.supplier,x.category,euro(x.amount_ht)])} heads={['Date','Établissement','Fournisseur','Famille','HT']}/></section>}
 {tab==='stocks'&&<section><div className="formCard"><h2>Stocks & inventaires</h2><p>Suivi du stock début, stock fin et calcul de la consommation matière réelle.</p></div></section>}
 {tab==='charges'&&<section><h2>Charges fixes</h2><Table rows={fc.slice(0,10).map(x=>[x.month,name(x.establishment_id),x.category,x.label,euro(x.amount)])} heads={['Mois','Établissement','Catégorie','Libellé','Montant']}/></section>}
 {tab==='historique'&&<section><h2>Historique</h2><Table rows={fs.map(x=>[x.business_date,name(x.establishment_id),euro(+x.lunch_sales_ht + +x.dinner_sales_ht),x.lunch_covers+x.dinner_covers])} heads={['Date','Établissement','CA HT','Couverts']}/></section>}</main>}
function Card({t,v}){return <article className="card"><span>{t}</span><strong>{v}</strong></article>}
function Table({heads,rows}){return <div className="table"><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>):<tr><td colSpan={heads.length}>Aucune donnée pour le moment.</td></tr>}</tbody></table></div>}
