'use client'
import {useEffect,useMemo,useState} from 'react'
import {createClient} from '@supabase/supabase-js'
const sb=createClient('https://ldwgsogeqreywbqulqyj.supabase.co','sb_publishable_heJuVcHJZcNkQm2w5Q2dIA_bUTPZTOE')
const euro=n=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(Number(n||0))
const pct=n=>`${(Number(n||0)*100).toFixed(1)} %`
export default function Home(){
 const [session,setSession]=useState(null),[profile,setProfile]=useState(null),[ests,setEsts]=useState([]),[sales,setSales]=useState([]),[invoices,setInvoices]=useState([]),[charges,setCharges]=useState([]),[stocks,setStocks]=useState([]),[tab,setTab]=useState('direction'),[msg,setMsg]=useState('')
 const [email,setEmail]=useState('b.oddos@gmail.com'),[password,setPassword]=useState('')
 const today=new Date().toISOString().slice(0,10),month=new Date().toISOString().slice(0,7)+'-01'
 const [sale,setSale]=useState({establishment_id:'',business_date:today,lunch_sales_ht:'',dinner_sales_ht:'',lunch_covers:'',dinner_covers:'',staff_hours:'',staff_cost:''})
 const [inv,setInv]=useState({establishment_id:'',invoice_date:today,supplier:'',category:'Épicerie',amount_ht:'',vat_amount:'',due_date:''})
 const [charge,setCharge]=useState({establishment_id:'',month,category:'Loyer',label:'',amount:''}),[stock,setStock]=useState({establishment_id:'',month,opening_stock_ht:'',closing_stock_ht:''})
 useEffect(()=>{sb.auth.getSession().then(({data})=>setSession(data.session));const {data:{subscription}}=sb.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[])
 useEffect(()=>{if(session)load();else setProfile(null)},[session])
 async function load(){const uid=session.user.id;const [{data:p},{data:e},{data:s},{data:i},{data:c},{data:st}]=await Promise.all([sb.from('profiles').select('*').eq('user_id',uid).single(),sb.from('establishments').select('*').eq('active',true),sb.from('daily_sales').select('*').order('business_date',{ascending:false}).limit(100),sb.from('supplier_invoices').select('*').order('invoice_date',{ascending:false}).limit(100),sb.from('fixed_charges').select('*').order('month',{ascending:false}).limit(100),sb.from('inventories').select('*').order('month',{ascending:false}).limit(50)]);setProfile(p);setEsts(e||[]);setSales(s||[]);setInvoices(i||[]);setCharges(c||[]);setStocks(st||[]);if(e?.[0]){for(const setter of [setSale,setInv,setCharge,setStock])setter(x=>({...x,establishment_id:x.establishment_id||e[0].id}))}}
 async function auth(mode){setMsg('');const r=mode==='login'?await sb.auth.signInWithPassword({email,password}):await sb.auth.signUp({email,password,options:{data:{full_name:'Bruno Oddos'}}});setMsg(r.error?r.error.message:mode==='login'?'Connexion réussie.':'Compte créé. Vérifiez votre e-mail si une confirmation est demandée.')}
 const totals=useMemo(()=>{const ca=sales.reduce((a,x)=>a+Number(x.lunch_sales_ht)+Number(x.dinner_sales_ht),0),covers=sales.reduce((a,x)=>a+x.lunch_covers+x.dinner_covers,0),personnel=sales.reduce((a,x)=>a+Number(x.staff_cost),0),achats=invoices.reduce((a,x)=>a+Number(x.amount_ht),0),fixes=charges.reduce((a,x)=>a+Number(x.amount),0);return{ca,covers,personnel,achats,fixes,result:ca-achats-personnel-fixes}},[sales,invoices,charges])
 async function save(table,payload,success,upsert=false,conflict=''){const q=upsert?sb.from(table).upsert(payload,{onConflict:conflict}):sb.from(table).insert(payload);const {error}=await q;setMsg(error?error.message:success);if(!error)load()}
 const uid=()=>session.user.id
 async function saveSale(e){e.preventDefault();await save('daily_sales',{...sale,lunch_sales_ht:+sale.lunch_sales_ht||0,dinner_sales_ht:+sale.dinner_sales_ht||0,lunch_covers:+sale.lunch_covers||0,dinner_covers:+sale.dinner_covers||0,staff_hours:+sale.staff_hours||0,staff_cost:+sale.staff_cost||0,created_by:uid()},'Journée enregistrée.',true,'establishment_id,business_date')}
 async function saveInv(e){e.preventDefault();await save('supplier_invoices',{...inv,amount_ht:+inv.amount_ht||0,vat_amount:+inv.vat_amount||0,due_date:inv.due_date||null,created_by:uid()},'Facture enregistrée.')}
 async function saveCharge(e){e.preventDefault();await save('fixed_charges',{...charge,amount:+charge.amount||0,created_by:uid()},'Charge enregistrée.')}
 async function saveStock(e){e.preventDefault();await save('inventories',{...stock,opening_stock_ht:+stock.opening_stock_ht||0,closing_stock_ht:+stock.closing_stock_ht||0,created_by:uid()},'Inventaire enregistré.',true,'establishment_id,month')}
 if(!session)return <main className="login"><section className="loginCard"><div className="brand">MAISON ODDOS</div><h1>Pilotage Restaurants</h1><p className="muted">Votre cockpit de gestion quotidien.</p><label>E-mail<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Mot de passe<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="8 caractères minimum"/></label><button onClick={()=>auth('login')}>Se connecter</button><button className="secondary" onClick={()=>auth('signup')}>Créer mon compte Direction</button>{msg&&<p className="message">{msg}</p>}</section></main>
 const name=id=>ests.find(e=>e.id===id)?.name||'—'
 return <main><header><div><div className="brand">MAISON ODDOS</div><h1>Pilotage Restaurants</h1></div><div className="user"><b>{profile?.full_name||session.user.email}</b><span>{profile?.role||'profil'}</span><button className="link" onClick={()=>sb.auth.signOut()}>Déconnexion</button></div></header><nav>{[['direction','Direction'],['saisie','Saisie rapide'],['factures','Factures'],['stocks','Stocks'],['charges','Charges'],['historique','Historique']].map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{l}</button>)}</nav>{msg&&<div className="toast">{msg}</div>}
 {tab==='direction'&&<section><div className="hero"><div><span>Situation consolidée</span><h2>{euro(totals.ca)}</h2><small>Chiffre d’affaires HT enregistré</small></div><div className="result"><span>Résultat estimé</span><strong>{euro(totals.result)}</strong></div></div><div className="grid"><Card t="Couverts" v={totals.covers}/><Card t="Ticket moyen" v={euro(totals.covers?totals.ca/totals.covers:0)}/><Card t="Achats matière" v={euro(totals.achats)} s={pct(totals.ca?totals.achats/totals.ca:0)}/><Card t="Personnel" v={euro(totals.personnel)} s={pct(totals.ca?totals.personnel/totals.ca:0)}/><Card t="Charges fixes" v={euro(totals.fixes)}/><Card t="Marge après charges" v={euro(totals.result)} s={pct(totals.ca?totals.result/totals.ca:0)}/></div><h3>Dernières journées</h3><Table rows={sales.slice(0,8).map(x=>[x.business_date,name(x.establishment_id),euro(+x.lunch_sales_ht + +x.dinner_sales_ht),x.lunch_covers+x.dinner_covers,euro(x.staff_cost)])} heads={['Date','Établissement','CA HT','Couverts','Personnel']}/></section>}
 {tab==='saisie'&&<Form title="Saisie de fin de service" onSubmit={saveSale}><Select ests={ests} value={sale.establishment_id} onChange={v=>setSale({...sale,establishment_id:v})}/><Field l="Date" type="date" v={sale.business_date} set={v=>setSale({...sale,business_date:v})}/><Field l="CA midi HT" type="number" v={sale.lunch_sales_ht} set={v=>setSale({...sale,lunch_sales_ht:v})}/><Field l="CA soir HT" type="number" v={sale.dinner_sales_ht} set={v=>setSale({...sale,dinner_sales_ht:v})}/><Field l="Couverts midi" type="number" v={sale.lunch_covers} set={v=>setSale({...sale,lunch_covers:v})}/><Field l="Couverts soir" type="number" v={sale.dinner_covers} set={v=>setSale({...sale,dinner_covers:v})}/><Field l="Heures équipe" type="number" v={sale.staff_hours} set={v=>setSale({...sale,staff_hours:v})}/><Field l="Coût personnel chargé" type="number" v={sale.staff_cost} set={v=>setSale({...sale,staff_cost:v})}/></Form>}
 {tab==='factures'&&<section><Form title="Nouvelle facture fournisseur" onSubmit={saveInv}><Select ests={ests} value={inv.establishment_id} onChange={v=>setInv({...inv,establishment_id:v})}/><Field l="Date facture" type="date" v={inv.invoice_date} set={v=>setInv({...inv,invoice_date:v})}/><Field l="Fournisseur" v={inv.supplier} set={v=>setInv({...inv,supplier:v})}/><label>Famille<select value={inv.category} onChange={e=>setInv({...inv,category:e.target.value})}>{['Viandes','Poissons','Fruits & légumes','Épicerie','Produits laitiers','Boissons','Vins','Autres'].map(x=><option key={x}>{x}</option>)}</select></label><Field l="Montant HT" type="number" v={inv.amount_ht} set={v=>setInv({...inv,amount_ht:v})}/><Field l="TVA" type="number" v={inv.vat_amount} set={v=>setInv({...inv,vat_amount:v})}/><Field l="Échéance" type="date" v={inv.due_date} set={v=>setInv({...inv,due_date:v})}/></Form><Table rows={invoices.slice(0,10).map(x=>[x.invoice_date,name(x.establishment_id),x.supplier,x.category,euro(x.amount_ht)])} heads={['Date','Établissement','Fournisseur','Famille','HT']}/></section>}
 {tab==='stocks'&&<Form title="Inventaire mensuel" onSubmit={saveStock}><Select ests={ests} value={stock.establishment_id} onChange={v=>setStock({...stock,establishment_id:v})}/><Field l="Mois" type="date" v={stock.month} set={v=>setStock({...stock,month:v.slice(0,7)+'-01'})}/><Field l="Stock début HT" type="number" v={stock.opening_stock_ht} set={v=>setStock({...stock,opening_stock_ht:v})}/><Field l="Stock fin HT" type="number" v={stock.closing_stock_ht} set={v=>setStock({...stock,closing_stock_ht:v})}/></Form>}
 {tab==='charges'&&<Form title="Charge fixe" onSubmit={saveCharge}><Select ests={ests} value={charge.establishment_id} onChange={v=>setCharge({...charge,establishment_id:v})}/><Field l="Mois" type="date" v={charge.month} set={v=>setCharge({...charge,month:v.slice(0,7)+'-01'})}/><label>Catégorie<select value={charge.category} onChange={e=>setCharge({...charge,category:e.target.value})}>{['Loyer','Énergie','Assurances','Comptable','Logiciels','Crédit / leasing','Communication','Entretien','Autres'].map(x=><option key={x}>{x}</option>)}</select></label><Field l="Libellé" v={charge.label} set={v=>setCharge({...charge,label:v})}/><Field l="Montant" type="number" v={charge.amount} set={v=>setCharge({...charge,amount:v})}/></Form>}
 {tab==='historique'&&<section><h2>Historique</h2><Table rows={sales.map(x=>[x.business_date,name(x.establishment_id),euro(+x.lunch_sales_ht + +x.dinner_sales_ht),x.lunch_covers+x.dinner_covers])} heads={['Date','Établissement','CA HT','Couverts']}/></section>}</main>}
function Card({t,v,s}){return <article className="card"><span>{t}</span><strong>{v}</strong>{s&&<small>{s} du CA</small>}</article>}
function Form({title,onSubmit,children}){return <section><div className="formCard"><h2>{title}</h2><form onSubmit={onSubmit}>{children}<button type="submit">Enregistrer</button></form></div></section>}
function Field({l,type='text',v,set}){return <label>{l}<input type={type} step={type==='number'?'0.01':undefined} value={v} onChange={e=>set(e.target.value)}/></label>}
function Select({ests,value,onChange}){return <label>Établissement<select value={value} onChange={e=>onChange(e.target.value)}>{ests.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}
function Table({heads,rows}){return <div className="table"><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>):<tr><td colSpan={heads.length}>Aucune donnée pour le moment.</td></tr>}</tbody></table></div>}