'use client'
import {useEffect,useState} from 'react'
import {createPortal} from 'react-dom'
import {createClient} from '@supabase/supabase-js'
const sb=createClient('https://ldwgsogeqreywbqulqyj.supabase.co','sb_publishable_heJuVcHJZcNkQm2w5Q2dIA_bUTPZTOE')
const euro=n=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(Number(n||0))
const input={width:'100%',boxSizing:'border-box',padding:9,marginTop:4}
export default function PersonnelManager(){
 const [user,setUser]=useState(null),[rows,setRows]=useState([]),[edit,setEdit]=useState(null),[msg,setMsg]=useState(''),[host,setHost]=useState(null)
 async function load(){const {data}=await sb.from('employees').select('*').order('full_name');setRows(data||[])}
 useEffect(()=>{sb.auth.getUser().then(({data})=>{setUser(data?.user||null);if(data?.user)load()})},[])
 useEffect(()=>{if(!user)return;const timer=setInterval(()=>{const b=[...document.querySelectorAll('nav button')].find(x=>x.textContent.trim()==='Personnel'),active=b?.classList.contains('active');let h=document.getElementById('personnel-manager');if(active&&!h){const s=[...document.querySelectorAll('main section')].find(x=>x.textContent.includes('Masse salariale')||x.textContent.includes('Salariés'));if(s){h=document.createElement('div');h.id='personnel-manager';s.appendChild(h)}}if(!active&&h){h.remove();h=null}setHost(h||null)},400);return()=>clearInterval(timer)},[user])
 async function save(e){e.preventDefault();const weekly=Number(edit.weekly_hours||0),net=Number(edit.net_salary||0),sal=Number(edit.employee_charge_rate||0),pat=Number(edit.employer_charge_rate||0),brut=sal<100?net/(1-sal/100):0,cost=brut+brut*pat/100,mh=weekly*52/12;const {error}=await sb.from('employees').update({full_name:edit.full_name.trim(),job_title:(edit.job_title||'').trim(),contract_type:edit.contract_type,weekly_hours:weekly,net_salary:net,employee_charge_rate:sal,employer_charge_rate:pat,monthly_loaded_cost:cost,hourly_cost:mh?cost/mh:0,active:edit.active}).eq('id',edit.id);if(error)return setMsg('Erreur : '+error.message);setMsg('✓ Salarié modifié.');setEdit(null);await load()}
 async function remove(r){if(!confirm(`Supprimer ${r.full_name} ?`))return;await sb.from('employee_hours').delete().eq('employee_id',r.id);const {error}=await sb.from('employees').delete().eq('id',r.id);if(error)return setMsg('Suppression impossible : '+error.message);setMsg('✓ Salarié supprimé.');setEdit(null);await load()}
 if(!user||!host)return null
 return createPortal(<div className="formCard" style={{marginTop:22}}><h3>Gestion des salariés</h3><p>Modifier ou supprimer une fiche salarié.</p>{msg&&<p><b>{msg}</b></p>}{rows.map(r=><div key={r.id} style={{borderTop:'1px solid #ddd',padding:'12px 0',display:'flex',gap:10,justifyContent:'space-between',alignItems:'center',flexWrap:'wrap'}}><div><b>{r.full_name}</b><div><small>{r.job_title||'—'} · {r.contract_type||'—'} · {euro(r.monthly_loaded_cost)}/mois · {euro(Number(r.monthly_loaded_cost||0)/22)}/jour</small></div></div><div style={{display:'flex',gap:8}}><button type="button" onClick={()=>setEdit({...r})}>Modifier</button><button type="button" onClick={()=>remove(r)}>Supprimer</button></div></div>)}{edit&&<form onSubmit={save} style={{marginTop:18,padding:16,border:'1px solid #ccc',borderRadius:12}}><h3>Modifier {edit.full_name}</h3><div className="grid"><label>Nom<input required value={edit.full_name||''} onChange={e=>setEdit({...edit,full_name:e.target.value})} style={input}/></label><label>Poste<input value={edit.job_title||''} onChange={e=>setEdit({...edit,job_title:e.target.value})} style={input}/></label><label>Contrat<select value={edit.contract_type||'CDI'} onChange={e=>setEdit({...edit,contract_type:e.target.value})} style={input}><option>CDI</option><option>CDD</option><option>Extra</option><option>Apprentissage</option></select></label><label>Heures / semaine<input type="number" step="0.01" value={edit.weekly_hours||''} onChange={e=>setEdit({...edit,weekly_hours:e.target.value})} style={input}/></label><label>Salaire net mensuel<input type="number" step="0.01" value={edit.net_salary||''} onChange={e=>setEdit({...edit,net_salary:e.target.value})} style={input}/></label><label>Charges salariales %<input type="number" step="0.01" value={edit.employee_charge_rate||''} onChange={e=>setEdit({...edit,employee_charge_rate:e.target.value})} style={input}/></label><label>Charges patronales %<input type="number" step="0.01" value={edit.employer_charge_rate||''} onChange={e=>setEdit({...edit,employer_charge_rate:e.target.value})} style={input}/></label><label>Actif <input type="checkbox" checked={!!edit.active} onChange={e=>setEdit({...edit,active:e.target.checked})}/></label></div><div style={{display:'flex',gap:8,marginTop:14}}><button type="submit">Enregistrer les modifications</button><button type="button" onClick={()=>setEdit(null)}>Annuler</button></div></form>}</div>,host)
}
